# Conclusion

Before diving into the project, we already had some expectation for the results based on our preexisting knowledge. For instance, we thought that a higher number of registered students would indicate a higher number of crimes. Nevertheless, the results from the exploratory data analysis turned out to be not what we expected. It turned out that the total number of registered students is actually uncorrelated with most of our variables of interest, which are the total number of crimes in different categories. The variable that is highly positively correlated with our variables of interest is actually the total number of schools, which we did not realize at first. 

Other than the surprising finding, we also were able to learn about some useful facts regarding school safety and crime issues in New York City public schools. By making the Cleveland dot plot and time series plots, we were able to observe which categories of crimes are more prevalent in schools. From the Cleveland dot plot and mosaic plot, we were able to analyze which boroughs or geographical districts have the highest number of crimes, which could be informative for families who prioritize safer school districts when finding a place to live. We also noticed that both the proportion regarding different categories of crimes and number of crimes among the boroughs did not really change over the years, which gave us the idea to make interactive components in D3 to display such results and verify our findings. Furthermore, after the exploration, we also have a better understanding of the underlying structure of schools among different boroughs in New York City and the association between our variables of interest and other variables such as number of schools and registered students. 

While we indeed acquired a better understanding of school safety and crime issues in New York City public schools, the data only includes information from 2013 to 2016, which could be considered relatively outdated and insufficient for further generalization and references. We believe the next step and future direction would be to collect data that are more recent and includes information over longer periods of time. In that case, the results would be more credible and relevant, which hopefully would help the audience to be more informed and familiar with the school safety issues in New York City public schools. 
