# Proposal

## Research topic

Nowadays, it is quite common to watch or read the news about crimes that take place in schools. A lot of dreadful incidents have happened in the environment that we are most familiar with. 
While discussing the topic of our final project, we thought we could take this opportunity to answer questions regarding the school safety issues in New York City, which would be more relevant as it is where we are currently located. Some example questions would be whether the crime rate in New York City schools has gone up over the years, whether the crime rate is higher in some specific boroughs, and if a higher number of registered students indicates higher crime rates. By analyzing the dataset and utilizing data visualization techniques, we are hoping to extract meaningful information regarding the school safety issues in New York City and answers to our questions.


## Data availability

While searching for datasets that could provide answers to our questions, we came across a few datasets that sparked our interest in NYC Open Data. One of them is the school safety report of New York City public schools from 2010 to 2016, and the other one is the school safety report of New York City public schools from 2015 to 2016. Both datasets include information like the number of crimes for different categories, boroughs where the location is situated, number of registered students at each location, and school year, indicating that they would be sufficient for us to analyze and extract answers and information regarding school safety issues in New York City. As we are also interested in the shift in crime rates over time, we decided to go with the one that is from 2010 to 2016. The data source is [2010-2016 School Safety Report]
(https://data.cityofnewyork.us/Education/2010-2016-School-Safety-Report/qybk-bjjc). We also noticed that there is the same dataset on Kaggle. The original data source link is no longer available, in this case, considering the reputation of NYC Open Data, we treat it as the source of our dataset. 

The data is collected by the New York City Police Department (NYPD) and is published by the New York City Department of Education (DOE). The NYPD is responsible for maintaining the crime data for incidents that occurred among public schools in New York City, which would then be provided to the DOE for compilation, indicating that maintenance of the data is a collaborative work by the NYPD and the DOE. The update frequency of the data is annually, and the last update was on September 16, 2017, which would make sense as the data only includes information from 2010 to 2016. As DOE is the main agency that is in charge of the data, we would try to get in touch with them if we have any questions about the data. 

The available formats of data include CSV, CSV for Excel, TSV for Excel, RDF, RSS, and XML. To conduct our analysis and apply data visualization techniques, we could download the data in the format of CSV and call functions like read.csv( ) to read our dataset for further analysis. 

While we do not notice any issues with data quality, we do notice that even though the data is claimed to be school safety reports from 2010 to 2016, the data only contains the fiscal year from 2013 to 2016. Nevertheless, we do not think that would affect the quality of the data and believe we would still be able to observe the change throughout the years, allowing us to still conduct a holistic analysis. While it is frustrating that the dataset itself doesn’t match the description, we decide to keep this dataset for our analysis anyway for several reasons. Since there are six thousand rows and thirsty columns, the dataset is an excellent material for us to practice various types of data analysis. While we do aware of the importance of the completeness of a dataset. For the sake of practicing, we decide to use this dataset as our class project.
